name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  push:
    name: "Push ${{ matrix.image }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
            - node-12-eas
            - node-14-eas
            - node-16-curl-tidy

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.image }}"
          push: true
          tags: ghcr.io/troopers/${{ matrix.image }}
